{"id":3972,"date":"2020-09-20T20:32:29","date_gmt":"2020-09-20T15:02:29","guid":{"rendered":"https:\/\/golangbyexamples.com\/?p=3972"},"modified":"2020-09-20T20:32:42","modified_gmt":"2020-09-20T15:02:42","slug":"panic-with-defer-golang","status":"publish","type":"post","link":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/","title":{"rendered":"Panic with Defer in Go (Golang)"},"content":{"rendered":"\n<div id=\"ez-toc-container\" class=\"ez-toc-v2_0_17 counter-hierarchy counter-decimal ez-toc-light-blue\">\n<div class=\"ez-toc-title-container\">\n<p class=\"ez-toc-title\">Table of Contents<\/p>\n<span class=\"ez-toc-title-toggle\"><a class=\"ez-toc-pull-right ez-toc-btn ez-toc-btn-xs ez-toc-btn-default ez-toc-toggle\" style=\"display: none;\"><i class=\"ez-toc-glyphicon ez-toc-icon-toggle\"><\/i><\/a><\/span><\/div>\n<nav><ul class=\"ez-toc-list ez-toc-list-level-1\"><li class=\"ez-toc-page-1 ez-toc-heading-level-1\"><a class=\"ez-toc-link ez-toc-heading-1\" href=\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#Overview\" title=\"Overview\">Overview<\/a><\/li><li class=\"ez-toc-page-1 ez-toc-heading-level-1\"><a class=\"ez-toc-link ez-toc-heading-2\" href=\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#Example\" title=\"Example\">Example<\/a><\/li><li class=\"ez-toc-page-1 ez-toc-heading-level-1\"><a class=\"ez-toc-link ez-toc-heading-3\" href=\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#Using_defer_to_recover_from_a_panic\" title=\"Using defer to recover from a panic\">Using defer to recover from a panic<\/a><\/li><\/ul><\/nav><\/div>\n<h1 class=\"wp-block-heading\"><span class=\"ez-toc-section\" id=\"Overview\"><\/span><strong>Overview<\/strong><span class=\"ez-toc-section-end\"><\/span><\/h1>\n\n\n\n<p class=\"has-medium-font-size\"><strong>defer<\/strong> function will be executed even if <strong>panic<\/strong> happens in a program.\u00a0In fact, <strong>defer<\/strong> function is the only function that is called after the <strong>panic. <\/strong>When the <strong>panic<\/strong> is raised in a function then the execution of that function is stopped and any deferred function will be executed. In fact deferred function in all the function calls in the stack will also be executed until all the functions have\u00a0returned. At that time the program will exit and it will print the panic message<\/p>\n\n\n\n<p class=\"has-medium-font-size\">So if a defer function is present then it will be executed and the control will\u00a0be\u00a0returned back to the caller function which will again execute its defer function if present and the chain goes on until the program exists.<\/p>\n\n\n\n<h1 class=\"wp-block-heading\"><span class=\"ez-toc-section\" id=\"Example\"><\/span><strong>Example<\/strong><span class=\"ez-toc-section-end\"><\/span><\/h1>\n\n\n\n<p class=\"has-medium-font-size\">Let&#8217;s see an example<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">package main\n\nimport \"fmt\"\n\nfunc main() {\n    defer fmt.Println(\"Defer in main\")\n    panic(\"Panic with Defer\")\n    fmt.Println(\"After painc in f2\")\n}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\"><strong>Output<\/strong><\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Defer in main\npanic: Panic Create\n\ngoroutine 1 [running]:\nmain.main()\n        \/Users\/slohia\/go\/src\/github.com\/golang-examples\/articles\/tutorial\/panicRecover\/deferWithPanic\/main.go:7 +0x95\nexit status 2<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">In the above program we have a <strong>defer<\/strong> function first and then we manually create the panic. As you can see from the output that defer function got executed as below line is printed in the output<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Defer in main<\/code><\/pre>\n\n\n\n<h1 class=\"wp-block-heading\"><span class=\"ez-toc-section\" id=\"Using_defer_to_recover_from_a_panic\"><\/span><strong>Using defer to recover from a panic<\/strong><span class=\"ez-toc-section-end\"><\/span><\/h1>\n\n\n\n<p class=\"has-medium-font-size\">Go provides a built-in function <strong>recover<\/strong> for recovering from a panic. Below is the signature of this function<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">func recover() interface{}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\"><strong>defer<\/strong> function is the only function that is called after the <strong>panic<\/strong>. So it makes sense to put the <strong>recover<\/strong> function in the <strong>defer<\/strong> function only. If the <strong>recover<\/strong>\u00a0 function is not within the\u00a0defer function then it will not stop <strong>panic<\/strong>.<\/p>\n\n\n\n<p class=\"has-medium-font-size\">Let&#8217;s see an example of recover<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">package main\n\nimport \"fmt\"\n\nfunc main() {\n\n\ta := []string{\"a\", \"b\"}\n\tcheckAndPrint(a, 2)\n\tfmt.Println(\"Exiting normally\")\n}\n\nfunc checkAndPrint(a []string, index int) {\n\tdefer handleOutOfBounds()\n\tif index > (len(a) - 1) {\n\t\tpanic(\"Out of bound access for slice\")\n\t}\n\tfmt.Println(a[index])\n}\n\nfunc handleOutOfBounds() {\n\tif r := recover(); r != nil {\n\t\tfmt.Println(\"Recovering from panic:\", r)\n\t}\n}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\"><strong>Output<\/strong><\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Recovering from panic: Out of bound access for slice\nExiting normally<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">In the above program we have a function <strong>checkAndPrint<\/strong> which checks and prints slice element at an index passed in the argument. If the index passed is greater than the length of the array\u00a0then the program panics.\u00a0 We have added a defer function named <strong>handleOutIfBounds<\/strong> as well at the start of the function <strong>checkAndPrint<\/strong>.\u00a0This function\u00a0contains\u00a0the\u00a0call to <strong>recover<\/strong> function\u00a0as below<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">if r := recover(); r != nil {\n    fmt.Println(\"Recovering from panic:\", r)\n}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">The <strong>recover<\/strong> function will catch the panic and we can also print the message from the panic.\u00a0<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Recovering from panic: Out of bound access for slice<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">After the <strong>recover<\/strong> function the program continues and the control returns to the called function which is\u00a0 <strong>main<\/strong> here. That is why we get output as<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Exiting normally<\/code><\/pre>\n","protected":false},"excerpt":{"rendered":"<p>Table of Contents OverviewExampleUsing defer to recover from a panic Overview defer function will be executed even if panic happens in a program.\u00a0In fact, defer function is the only function that is&#8230;<\/p>\n","protected":false},"author":1,"featured_media":0,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"standard","meta":{"spay_email":"","footnotes":"","jetpack_publicize_message":"","jetpack_is_tweetstorm":false},"categories":[1],"tags":[3,4],"class_list":["post-3972","post","type-post","status-publish","format-standard","hentry","category-tech","tag-go","tag-golang"],"yoast_head":"<!-- This site is optimized with the Yoast SEO plugin v22.7 - https:\/\/yoast.com\/wordpress\/plugins\/seo\/ -->\n<title>Panic with Defer in Go (Golang) - Welcome To Golang By Example<\/title>\n<meta name=\"robots\" content=\"index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1\" \/>\n<link rel=\"canonical\" href=\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/\" \/>\n<meta property=\"og:locale\" content=\"en_US\" \/>\n<meta property=\"og:type\" content=\"article\" \/>\n<meta property=\"og:title\" content=\"Panic with Defer in Go (Golang) - Welcome To Golang By Example\" \/>\n<meta property=\"og:description\" content=\"Table of Contents OverviewExampleUsing defer to recover from a panic Overview defer function will be executed even if panic happens in a program.\u00a0In fact, defer function is the only function that is...\" \/>\n<meta property=\"og:url\" content=\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/\" \/>\n<meta property=\"og:site_name\" content=\"Welcome To Golang By Example\" \/>\n<meta property=\"article:published_time\" content=\"2020-09-20T15:02:29+00:00\" \/>\n<meta property=\"article:modified_time\" content=\"2020-09-20T15:02:42+00:00\" \/>\n<meta name=\"author\" content=\"admin\" \/>\n<meta name=\"twitter:card\" content=\"summary_large_image\" \/>\n<meta name=\"twitter:label1\" content=\"Written by\" \/>\n\t<meta name=\"twitter:data1\" content=\"admin\" \/>\n\t<meta name=\"twitter:label2\" content=\"Est. reading time\" \/>\n\t<meta name=\"twitter:data2\" content=\"2 minutes\" \/>\n<script type=\"application\/ld+json\" class=\"yoast-schema-graph\">{\"@context\":\"https:\/\/schema.org\",\"@graph\":[{\"@type\":\"WebPage\",\"@id\":\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/\",\"url\":\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/\",\"name\":\"Panic with Defer in Go (Golang) - Welcome To Golang By Example\",\"isPartOf\":{\"@id\":\"https:\/\/golangbyexamples.com\/#website\"},\"datePublished\":\"2020-09-20T15:02:29+00:00\",\"dateModified\":\"2020-09-20T15:02:42+00:00\",\"author\":{\"@id\":\"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f\"},\"breadcrumb\":{\"@id\":\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#breadcrumb\"},\"inLanguage\":\"en-US\",\"potentialAction\":[{\"@type\":\"ReadAction\",\"target\":[\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/\"]}]},{\"@type\":\"BreadcrumbList\",\"@id\":\"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#breadcrumb\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"name\":\"Home\",\"item\":\"https:\/\/golangbyexamples.com\/\"},{\"@type\":\"ListItem\",\"position\":2,\"name\":\"Panic with Defer in Go (Golang)\"}]},{\"@type\":\"WebSite\",\"@id\":\"https:\/\/golangbyexamples.com\/#website\",\"url\":\"https:\/\/golangbyexamples.com\/\",\"name\":\"Welcome To Golang By Example\",\"description\":\"\",\"potentialAction\":[{\"@type\":\"SearchAction\",\"target\":{\"@type\":\"EntryPoint\",\"urlTemplate\":\"https:\/\/golangbyexamples.com\/?s={search_term_string}\"},\"query-input\":\"required name=search_term_string\"}],\"inLanguage\":\"en-US\"},{\"@type\":\"Person\",\"@id\":\"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f\",\"name\":\"admin\",\"image\":{\"@type\":\"ImageObject\",\"inLanguage\":\"en-US\",\"@id\":\"https:\/\/golangbyexamples.com\/#\/schema\/person\/image\/\",\"url\":\"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g\",\"contentUrl\":\"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g\",\"caption\":\"admin\"},\"url\":\"https:\/\/golangbyexamples.com\/author\/admin\/\"}]}<\/script>\n<!-- \/ Yoast SEO plugin. -->","yoast_head_json":{"title":"Panic with Defer in Go (Golang) - Welcome To Golang By Example","robots":{"index":"index","follow":"follow","max-snippet":"max-snippet:-1","max-image-preview":"max-image-preview:large","max-video-preview":"max-video-preview:-1"},"canonical":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/","og_locale":"en_US","og_type":"article","og_title":"Panic with Defer in Go (Golang) - Welcome To Golang By Example","og_description":"Table of Contents OverviewExampleUsing defer to recover from a panic Overview defer function will be executed even if panic happens in a program.\u00a0In fact, defer function is the only function that is...","og_url":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/","og_site_name":"Welcome To Golang By Example","article_published_time":"2020-09-20T15:02:29+00:00","article_modified_time":"2020-09-20T15:02:42+00:00","author":"admin","twitter_card":"summary_large_image","twitter_misc":{"Written by":"admin","Est. reading time":"2 minutes"},"schema":{"@context":"https:\/\/schema.org","@graph":[{"@type":"WebPage","@id":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/","url":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/","name":"Panic with Defer in Go (Golang) - Welcome To Golang By Example","isPartOf":{"@id":"https:\/\/golangbyexamples.com\/#website"},"datePublished":"2020-09-20T15:02:29+00:00","dateModified":"2020-09-20T15:02:42+00:00","author":{"@id":"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f"},"breadcrumb":{"@id":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https:\/\/golangbyexamples.com\/panic-with-defer-golang\/"]}]},{"@type":"BreadcrumbList","@id":"https:\/\/golangbyexamples.com\/panic-with-defer-golang\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/golangbyexamples.com\/"},{"@type":"ListItem","position":2,"name":"Panic with Defer in Go (Golang)"}]},{"@type":"WebSite","@id":"https:\/\/golangbyexamples.com\/#website","url":"https:\/\/golangbyexamples.com\/","name":"Welcome To Golang By Example","description":"","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https:\/\/golangbyexamples.com\/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"Person","@id":"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f","name":"admin","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https:\/\/golangbyexamples.com\/#\/schema\/person\/image\/","url":"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g","contentUrl":"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g","caption":"admin"},"url":"https:\/\/golangbyexamples.com\/author\/admin\/"}]}},"jetpack_featured_media_url":"","jetpack_publicize_connections":[],"jetpack_sharing_enabled":true,"jetpack_shortlink":"https:\/\/wp.me\/paOs1b-124","amp_validity":null,"amp_enabled":true,"_links":{"self":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts\/3972","targetHints":{"allow":["GET"]}}],"collection":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/comments?post=3972"}],"version-history":[{"count":1,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts\/3972\/revisions"}],"predecessor-version":[{"id":3973,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts\/3972\/revisions\/3973"}],"wp:attachment":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/media?parent=3972"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/categories?post=3972"},{"taxonomy":"post_tag","embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/tags?post=3972"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}